### ISSUE TITLE
Specificying fields in arrays

### ISSUE THREAD

**Issue by hubertrogers** [cameronhunter/jsonymize#1]
Brilliant tool, but does specifying/excluding field names in arrays work?

**Comment by cameronhunter** [comment]
I'm not sure what you mean – do you mean you want to target a particular item in the array to anonymize or that you want the whole array of data to be anonymized? Can you provide an example?

**Comment by hubertrogers** [comment]
Hi! Say I had an array of the objects, each like this example below:
```
{
    "topfield1": "foo",
    "topfield2": "bar",
    "topfield3": {
        "subfield1": "hoo",
        "subfield1": "har",
    },
    "topfield4": [{
        "objectinarrayfield1": "goo",
        "objectinarrayfield2": "gar"
    }, {
        "objectinarrayfield3": "joo",
        "objectinarrayfield4": "jar"
    }]
}
```

As far as I could figure out, jsonymize currently lets me anonymize e.g., 'topfield1', but not 'subfield1' or 'objectinarrayfield1'.

**Comment by cameronhunter** [comment]
The paths that you pass to `jsonymize` are [JSONPaths](https://github.com/jayway/JsonPath). You should be able to anonymize the fields you're interested in using:

```bash
$ cat hubertrogers.json | jsonymize topfield3.subfield1 topfield4.*.objectinarrayfield1
```
